[package]
name = "rust-test-shared-app-state"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "2.0.1"
tokio = { version = "1.22.0", features = ["full"] }
strum_macros = "0.24.3"